CREATE DATABASE crawler;

DROP TABLE IF EXISTS crawler;
CREATE TABLE IF NOT EXISTS crawler (
    id INT AUTO_INCREMENT PRIMARY KEY,
    host varchar(255) ,
    description varchar(255),
    createDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modifyDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleteYn TINYINT DEFAULT 0,
    FOREIGN KEY (host) REFERENCES seed(host)
);

DROP TABLE IF EXISTS seed;
CREATE TABLE IF NOT EXISTS seed (
    host varchar(255) PRIMARY KEY,
    crawlDelay int DEFAULT 30,
    createDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleteYn TINYINT DEFAULT 0
);

--

DROP TABLE IF EXISTS seed_link;
CREATE TABLE IF NOT EXISTS seed_link (
    url varchar(255) PRIMARY KEY,
    visitDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    createDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleteYn TINYINT DEFAULT 0
);